import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync('app/src/main/assets/apps/shared/amy-local-assistant.js','utf8');
function runtime(values={}){const c={setTimeout,clearTimeout,URL,localStorage:{getItem:k=>values[k]??null}};c.window=c;vm.createContext(c);vm.runInContext(source,c);vm.runInContext(fs.readFileSync('app/src/main/assets/apps/shared/amy-local-knowledge.js','utf8'),c);return c;}
test('empty data never invents market or journal',async()=>{const c=runtime();assert.match((await c.AmyLocalAssistant.ask('harga mapping')).text,/Belum ada snapshot/);assert.match((await c.AmyLocalAssistant.ask('jurnal saya')).text,/Belum ada jurnal/);});
test('old snapshots force WAIT and hide actionable price levels',()=>{const a=runtime().AmyLocalAssistant;const t=a.mapping('entry mapping',{tf:'M5',fresh:true,sourceTime:10,signal:'BUY',plan:{entry:999,sl:1,tp:2000}},Date.now());assert.match(t,/WAIT/);assert.doesNotMatch(t,/Entry 999/);});
test('fresh market context describes evidence without a trade entry',()=>{const now=Date.now(),c=runtime({'amyfx.market-context.v1':JSON.stringify({version:'amyfx-gold-context-v1',fresh:true,source:{M1:now/1000-60},h1:{bias:'BULLISH',health:'WEAKENING'},m15:{control:'SELLER'},m1:{status:'WAITING'},primary:{label:'BELI GOLD',area:{low:2490,high:2495},invalidation:2480},execution:{status:'NOT READY',reason:'M15 berlawanan arah.'}})});const t=c.AmyLocalAssistant.mapping('mapping',null,now);assert.match(t,/2\.490/);assert.match(t,/belum siap|Belum siap|BELUM SIAP/);assert.doesNotMatch(t,/entry historis|Belum fill/);});
test('journal analytics use actual journal outcomes and amounts',async()=>{const c=runtime({'tradingLibraryManager.journals.v1':JSON.stringify([{result:'Win',profit:100},{result:'Loss',loss:40},{result:'BE'},{result:'Belum selesai'}])});const r=await c.AmyLocalAssistant.ask('evaluasi jurnal saya');assert.match(r.text,/4 transaksi; 1 win, 1 loss, 1 BE, 1 belum/);assert.match(r.text,/33,33%/);assert.match(r.text,/selisih 60/);assert.doesNotMatch(r.text,/snapshot Mapping/);});
test('journal setup questions do not route into market',()=>{assert.deepEqual(Array.from(runtime().AmyLocalAssistant.intent('setup jurnal saya')),['journal']);});
test('progress uses actual attempt records and review topics',async()=>{const c=runtime({'amy_read_topics':'["a","a","b"]','amy-guided-v2-summary':JSON.stringify({results:[{correct:true},{correct:false}],review:[{title:'FVG'}]})});const t=(await c.AmyLocalAssistant.ask('progres belajar saya')).text;assert.match(t,/2 bagian/);assert.match(t,/1\/2 benar/);assert.match(t,/ulang: FVG/);assert.match(t,/bukan bukti menguasai/);});
test('news remains a timestamped cached feed and supports keyword filtering',async()=>{const c=runtime({'amyfx.assistant.news.v1':JSON.stringify({updated:'2026-09-13T00:00:00Z',items:[{text:'Inflasi CPI meningkat',time:'2026-09-13T00:00:00Z'},{text:'Gold melemah'}]})});const t=(await c.AmyLocalAssistant.ask('berita CPI')).text;assert.match(t,/Inflasi CPI/);assert.doesNotMatch(t,/Gold melemah/);assert.match(t,/salinan feed terakhir/);});
test('concept queries retrieve packaged lessons instead of unrelated live mapping',async()=>{const c=runtime();const t=await c.AmyLocalAssistant.ask('apa itu FVG');assert.match(t.text,/Dari materi Academy/);assert.ok(t.links[0].path.startsWith('apps/academy/'));assert.doesNotMatch(t.text,/Belum ada snapshot/);});
test('follow-up retains last data topic',async()=>{const c=runtime();await c.AmyLocalAssistant.ask('progres belajar');assert.match((await c.AmyLocalAssistant.ask('jelaskan lagi')).text,/Catatan belajar/);});
test('unsupported question does not fabricate an answer',async()=>{assert.match((await runtime().AmyLocalAssistant.ask('resep nasi goreng')).text,/belum bisa menentukan/);});
test('no provider requests in local assistant and public OS ask delegates locally',()=>{assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|AmyNativeAI|callProvider/);const blueprint=fs.readFileSync('app/src/main/assets/apps/shared/amyfx-blueprint-v1.js','utf8');const ask=blueprint.slice(blueprint.indexOf('  async function ask('),blueprint.indexOf('  let mentor ='));assert.doesNotMatch(ask,/callProvider/);assert.match(ask,/AmyLocalAssistant.ask/);});
test('all active module entry points load local assistant',()=>{for(const p of ['index.html','apps/mapping/index.html','apps/market-intel/index.html','apps/journal/index.html','apps/academy/index.html']){const text=fs.readFileSync('app/src/main/assets/'+p,'utf8');assert.match(text,/amy-local-assistant.js/);assert.doesNotMatch(text,/src="[^"]*amyfx-provider-detection/);}});
test('server context is persisted for cross-page access and old mapping plans are retired',()=>{const mapping=fs.readFileSync('app/src/main/assets/apps/mapping/js/ict-workspace/app.js','utf8');const panel=fs.readFileSync('app/src/main/assets/apps/mapping/js/ict-workspace/context-panel.js','utf8');assert.match(mapping,/localStorage.removeItem\('amyfx.ict.mapping.v1'/);assert.match(panel,/localStorage.setItem\('amyfx.market-context.v1'/);assert.match(panel,/currentContext\(payload\)/);});

test('natural-language reading and news questions keep relevant intent',async()=>{const c=runtime({'amyfx.assistant.news.v1':JSON.stringify({items:[{text:'Gold menguat'}]})});assert.match((await c.AmyLocalAssistant.ask('ada berita apa sekarang')).text,/Gold menguat/);assert.match((await c.AmyLocalAssistant.ask('terakhir aku baca apa')).text,/Catatan belajar/);assert.match((await c.AmyLocalAssistant.ask('jelasin FVG dong')).text,/Dari materi Academy/);});
